### ISSUE TITLE
Automatic creation of staggered versioned tags

### ISSUE THREAD

**Issue by J12934** [docker/build-push-action#13]
I'd would be cool if there was a option for this action to automatically split the version of the git reference version up and create multiple docker tags based on the major and minor version numbers of the git reference.

For example: `refs/tags/v1.3.1` would turn into

- `v1.3.1`
- `v1.3`
- `v1`

Sorry don't know if there is a proper name for this practice 😅 But this seems to be common among the more popular images.

**Comment by zappy-shu** [comment]
Hi @J12934. Thank you for your feedback. I've put this on our backlog to look into.

The only issue I can see is if you do a patch for a previous minor version. For example if you already have a `v1.0.0` and then create a `v1.1.0` everything will be as expected: `v1` will point to the latest `v1.0.0`.

If you then push a patch to the original version `v1.0.1` then `v1` will now point to this image rather than the latest version. @justincormack any thoughts?

**Comment by J12934** [comment]
Oh that's a good point, didn't think of that. Might require to look into the repositories release history to see which tags to set and which to skip.
