### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by aviramha** [docker/build-push-action#137]
Thanks for this great action!

I had blew my mind when seeing the new documentation and didn't understand why my action works if it doesn't conform to it. 
It turns out the documentation shown on https://github.com/marketplace/actions/build-and-push-docker-images is of v2, but the recommend of the latest is 1.1.1.
This is very confusing, not sure how to fix it but I think it may cause troubles for other people too not realizing they use the wrong docs with wrong build.

**Comment by crazy-max** [comment]
@aviramha 

v2 is currently in beta through a mutable tag, that's why the marketplace only shows the latest release v1.1.1:

![image](https://user-images.githubusercontent.com/1951866/93993879-ce798b00-fd7e-11ea-925e-7b379538edfd.png)

The v2.0.0 release that should arrive shortly will solve this problem. In the meantime please stick to what is defined in the README.
