### ISSUE TITLE
Docker login to private registry prior to build

### ISSUE THREAD

**Issue by dezpriest** [docker/build-push-action#15]
Hi,
Thanks for the GitHub action! :)
I am trying to build an image based on private image which is available in same repo we use to push.

Currently it looks like  **'login'** to the private registry happens before **'push'** but after **'build'** steps. 
Is it possible to shift the 'login' step to happen 'build' step?

Thanks!

**Comment by dezpriest** [comment]
I digged a bit and looks like we need to slightly change order in this source file
https://github.com/docker/github-actions/blob/master/cmd/build_push.go

**Comment by zappy-shu** [comment]
Hi @dezpriest. Thanks for looking into this. I believe you are right and will make the change ASAP

**Comment by zappy-shu** [comment]
This should now be fixed

**Comment by danieldiazastudillo** [comment]
I was having some issues pushing my image to the registry because of some login problem. I'm new to GitHub Actions and to these days, i've never really used GitHub Secrets. I was using this Action without any observations, problems arised when using in another repository. I forgot that **Github Secrets are different for every repository** so, the Action could not push the image to the Docker registry for obvious reasons.

I don't know if the current Actions API allow this but, it would be nice that the Action notifies if it's using a Secret variable that doesn't exist. It just skipped the login step and built the image, failing in the last step, pushing the image.
