### ISSUE TITLE
Add Example Of How To Pass build-args

### ISSUE THREAD

**Issue by ogomaemmanuel** [docker/build-push-action#174]
I am having trouble passing build-arg in the __step.with__, would please add an example in the doc. Thanks

**Comment by crazy-max** [comment]
@ogomaemmanuel Types are defined in the [inputs section](https://github.com/docker/build-push-action#inputs) of the README. Here `build-args` is `List` type whose syntax can be found at the bottom of the table.

**Comment by Samahu** [comment]
Hi @crazy-max I have two build args specified in my github workflow as you specified but I keep getting "parse stage name ... invalid reference format." Checking the logs I see that the docker-build-push action passes the two arguments as one. What am I missing?

You can view the problem here: https://github.com/Samahu/OceanWATERS/runs/1289042444?check_suite_focus=true

**Comment by crazy-max** [comment]
@Samahu 

Replace

```yaml
build-args: BASE_DOCKER_IMAGE=${{ matrix.config.base_image }}, ROS_DISTRO=${{ matrix.config.ros_distro }}
```

With

```yaml
build-args: |
  BASE_DOCKER_IMAGE=${{ matrix.config.base_image }}
  ROS_DISTRO=${{ matrix.config.ros_distro }}
```

**Comment by Samahu** [comment]
You are right .. I had two build steps .. I changed one and forgot about the other.. I will try again .. thanks!
