### ISSUE TITLE
Increment docker image tag automatically

### ISSUE THREAD

**Issue by Forbzy** [docker/build-push-action#434]
I don't know if this is a feature that already exists or needs to be added but I'll say what I'm trying to do.
Say I have an existing docker image [DOCKER IMAGE]:1.x.x on docker hub. I would like the Github Action to recognise the 1.x.x in docker  hub or any private repo and add it to the metadata. Then increment it by the patch, minor or major version number when doing a docker push. So if I start with [DOCKER IMAGE]:1.0.0 I'll end up pushing [DOCKER IMAGE]:1.0.1 or [DOCKER IMAGE]:1.1.0 [DOCKER IMAGE]:2.0.0 automatically.

Is there any way to achieve this currently? This would remove a bit of operational overhead.

**Comment by Forbzy** [comment]
Sorry to pull you in @crazy-max. Any guidance on this?

**Comment by crazy-max** [comment]
> I would like the Github Action to recognise the 1.x.x in docker hub

`build-push-action` is a wrapper of [buildx](https://github.com/docker/buildx) and it shouldn't add extra flavors like this. That's why [metadata-action](https://github.com/docker/metadata-action) has been created to [generated tags and labels](https://github.com/docker/build-push-action/blob/master/docs/advanced/tags-labels.md) for example.

Also I don't see how we could do that as part of the build. Let's say you have 1.0.0 and 2.0.0 on Hub. What do you want to bump?

**Comment by Forbzy** [comment]
Maybe we could set it to bump it by 1. So if you had 1.0.0 on hub, then when you push you would end up with 1.0.1

It doesn't need to be a part of the docker build part. Sorry I didn't explain it well. I just wanted to make sure it was in the docker push part. So maybe as part of docker push we check what already exists and bump by 1.

**Comment by crazy-max** [comment]
I think this is an [XY Problem](https://xyproblem.info/) here..

> Maybe we could set it to bump it by 1. So if you had 1.0.0 on hub, then when you push you would end up with 1.0.1

We don't know what is on Docker Hub or other registries because we don't have the information of all available Docker tags for a repository in this action. You could also have 3.0.0, 2.0.0, 1.0.0 on the registry so again what should be bumped?

> It doesn't need to be a part of the docker build part.

This action only uses buildx as [I said](https://github.com/docker/build-push-action/issues/434#issuecomment-900295048). That's why we use other actions like [metadata-action](https://github.com/docker/metadata-action) or something else. to generate tags, labels based on Git reference and GitHub events.

> I just wanted to make sure it was in the docker push part. So maybe as part of docker push we check what already exists and bump by 1.

We can't. The builder doing build and push is part of the same flow.

> So maybe as part of docker push we check what already exists and bump by 1. Or maybe the checking could happen as part of the metadata-action.

Maybe it could part of the [metadata-action](https://github.com/docker/metadata-action) but I don't think this feature should check on Docker tags but Git tags instead.

**Comment by Forbzy** [comment]
I actually like the idea of it checking against git tags instead. This way we are keeping git as the one source of truth. And you don't have to rely on docker hub or any other docker repository. 

Do we already have the ability to create a docker tag based on the git tag?
