### ISSUE TITLE
How to share layers with Docker Compose?

### ISSUE THREAD

**Issue by Bilge** [docker/build-push-action#493]
I am interested in this plugin solely for the caching aspect. I can get it to build and cache my layers to GHCR, but then when I run Docker Compose it just builds it all over again. How can I ensure that if I have already built my image using this plugin that Docker Compose will not duplicate the work?

**Comment by crazy-max** [comment]
@Bilge

> but then when I run Docker Compose

Which compose version (v1 or v2)?

If we talk about compose v2, indeed it uses buildx api under the hood but [only with the default driver (docker)](https://github.com/docker/compose/blob/125752c1272132737d76aac69bad5d430179d4e3/pkg/compose/build_buildkit.go#L30-L31) so it cannot reuse cache from your [`docker-container` driver](https://github.com/docker/buildx/blob/master/docs/reference/buildx_create.md#driver).

Maybe compose could be smart enough and use the current builder instead of the default one (cc @ndeloof @ulyssessouza).

**Comment by Bilge** [comment]
I thought I was using Docker Compose with Buildx support (blue console output) but it seems not?

>docker-compose -v

`docker-compose version 1.29.2, build 5becea4c`

**Comment by factoidforrest** [comment]
I happen to have come across this post while trying to do the exact same thing.  For my use, im just passing the cache arguments directly to buildx like `build --cache-from` and not using this lib, just it was extremely helpful to read.  

docker-compose may not support the containerized driver(docker-container), or at least I can find a setting for it.  However, `docker buildx bake` is a command designed to read compose files and do just what docker-compose does, but faster and using buildx.  So that is what I am investigating now.  

This question is a bit unrelated but does anyone know why the docs for this lib show using the git commit SHA as a key for the cache?  That's not going to be very useful for most workflows since they typically will build on a new commit each time.  Why not just set the key to something static and then let docker figure out if it should use its own cache for not?

**Comment by crazy-max** [comment]
> But actually, I guess it doesn't matter what version I'm running locally, since the only thing that matters is what's installed on the GitHub build agent.

Current runners embed both compose v1 (`docker-compose`) and v2 compose plugin (`docker compose`):

Seems like [compose v2 is packaged by Microsoft as deb pkg `moby-compose`](https://github.com/actions/virtual-environments/blob/b665bad57bcd15dfcdb4d951e164a0f9cc67e36f/images/linux/scripts/installers/docker-moby.sh#L19) on Ubuntu runners like the engine, cli and buildx (cc @cpuguy83).

**Comment by kroehre** [comment]
@Bilge we ran into this issue and were able to resolve by adding `load: true` to docker/build-push-action. see https://github.community/t/use-docker-layer-caching-with-docker-compose-build-not-just-docker/156049/3
