### ISSUE TITLE
What does `always_pull` do?

### ISSUE THREAD

**Issue by uduse** [docker/build-push-action#55]
My guess is that pulling a previously built image will facilitate layer-reusing, like using the old image as a cache. Am I right?

**Comment by paullaffitte** [comment]
It looks like it what it is actually doing yes. I use this option alongside with `cache_froms: organization/image`.

**Comment by missinglink** [comment]
Found my way here after reading the docs and wondering the same thing...

I read it as meaning:
> Attempt to first pull the image and use the build-cache where possible to avoid building the exact same thing twice (or parts of it)

.. although if that is correct I don't see why it would be `false` by default 🤷‍♂️

**Comment by missinglink** [comment]
hmm unfortunately not, I enabled `always_pull: true` after having successfully published the same action previously and it still ran the whole build (~15mins) again.

my understanding is that the build cache is not stored in the published images anyway, so I'm not sure if that's even possible?

really not sure what the purpose of `always_pull` is 😕

**Comment by missinglink** [comment]
Down the rabbit hole.. the Go code appends `--pull` to [docker build](https://docs.docker.com/engine/reference/commandline/build/), the documentation for it also just says:
> Always attempt to pull a newer version of the image

Got an answer from [this Stackoverflow post](https://stackoverflow.com/questions/58488535/whats-the-purpose-of-docker-build-pull)

Essentially `always_pull` is used for the case where you have a locally built version of that specific tag (which could be old, like an old `ubuntu:latest` on your HDD) but you'd prefer that the build step pulled the newest one before running `docker build`.

So for GH actions it's not relevant, as either you've published the baseimage in a previous step (meaning it would be pulled down again) or you don't have the baseimage locally and it would be pulled as part of `docker build`.

IMO it could probably be removed, or at least better documented since we both assumed the wrong thing.

**Comment by crazy-max** [comment]
@missinglink 

> IMO it could probably be removed, or at least better documented since we both assumed the wrong thing.

This input has been renamed `pull` in [build-push-action v2](https://github.com/docker/build-push-action/tree/v2-build-push) (#92) to be more consistent. You can already try it by combining it with:

* https://github.com/docker/setup-buildx-action
* https://github.com/docker/setup-qemu-action
* https://github.com/docker/login-action

**Comment by crazy-max** [comment]
Version 2 has been [merged to the main branch](https://github.com/docker/build-push-action#readme) and is therefore available via `uses: docker/build-push-action@v2` (mutable tag).

As a reminder, this new version changes drastically and works with 3 new actions ([login](https://github.com/docker/login-action#readme), [setup-buildx](https://github.com/docker/setup-buildx-action#readme) and [setup-qemu](https://github.com/docker/setup-qemu-action#readme)) that we have created. Many [usage examples](https://github.com/docker/build-push-action#usage) have been added to handle most use cases.

And it should fix this current issue. Don't hesitate if you have any questions.
