### ISSUE TITLE
using s3 cache with the action

### ISSUE THREAD

**Issue by Tirke** [docker/build-push-action#647]
I'm sorry this is totally a question not a bug.

Is the action automatically covering all the functionalities of buildkit?
My docker cache is too big for what Github allows and I'm wondering if I can invest some time trying out the s3 cache or do you need to update some stuff with the action before?

https://github.com/moby/buildkit#s3-cache-experimental

**Comment by jedevc** [comment]
The S3 remote cache isn't in an official release yet of buildkit - it was added in this commit [here](https://github.com/moby/buildkit/pull/2824/commits/09c5a7c0eeb144955600c1565ade9b90011d813c), and wasn't part of the 0.10 release series.

If you want to, you can try out the S3 cache on an experimental release using the `nightly` or `master` builds on buildkit [here](https://hub.docker.com/r/moby/buildkit/tags). To use them, you can configure the setup-buildx action to use `image=moby/buildkit:master` in `--driver-opts` - see [here](https://github.com/docker/setup-buildx-action#inputs) for more details.

Following that, you should be able to use the S3 cache in https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md, though there aren't proper docs yet, since it's still experimental.

If you're happy to try it out, the extra eyes and feedback would be *super* helpful, and really appreciated :heart:

**Comment by Tirke** [comment]
@jedevc I took some time to try it out. Works great on my initial testing and it's a great way to circumvent the very low amount of cache available on Github when you are building big images.

My only complaint would be around authentication to AWS. I'm used to OIDC auth + using 
`aws-actions/configure-aws-credentials@v1` and `role-to-assume` but I didn't find a way to make the buildkit daemon aware of the variables created by that action. Something like that `access_key_id=${{ env.AWS_ACCESS_KEY_ID }},secret_access_key=${{ env.AWS_SECRET_ACCESS_KEY }},aws_session_token=${{ env.AWS_SESSION_TOKEN }}` doesn't work. But creating a dedicated IAM user with credentials works.

This is a really useful feature for us, thanks :)

**Comment by jedevc** [comment]
Thanks for test driving it :tada:

So I think buildkitd should pick up on those environment variables - but I think the reason it might not be getting picked up in your case might be because the docker-container builder that the setup-buildx action creates won't set those environment variables in the container.

When the feature makes it into a buildkit release and the actions are updated to include it, we'll need to make sure that those credentials are properly propagated through. I'll re-open this issue for now, just so it doesn't get lost :smile:

**Comment by jedevc** [comment]
@stalkerg https://github.com/docker/buildx/pull/1294 was merged after the previous release of buildx, so you'll need to use a development build of buildx if you're wanting to use client-side credentials.

If your issue is still occurring even off of the buildx master branch, then please open a separate issue! :tada:

**Comment by mmospanenko** [comment]
having `GetObject, https response error StatusCode: 403` on Minio... Maybe there are any guides how to configure?
