### ISSUE TITLE
Warning on subdirectory usage leaves out mitigation options

### ISSUE THREAD

**Issue by almereyda** [docker/build-push-action#673]
#### Steps to reproduce this issue

1. Use the build-push-action with choosing a subdirectory from git context.
2. Recognise the warning about the BuildKit version, but without finding any reference to build kit, leave it where it is.

#### Expected behaviour

The build runs, and the correct BuildKit is chosen.

#### Actual behaviour

The error message "subdirectories are not yet supported" is thrown.

### Mitigation

The warning is a little passive aggressive, as it does state the problem, but no solution. Following the suggested requirements of the action, the expected behaviour can be achieved when using the [`setup-buildx-action`](https://github.com/docker/setup-buildx-action). For a new user of GitHub actions, like me, it is not obvious that this action will bring the correct BuildKit version >0.9, as required by the warning.

Some written help in finding this little additional setting to be made when wanting to use subdirectories would be very much appreciated.

**Comment by crazy-max** [comment]
If you're using the `docker` builder (default if `setup-buildx-action` not used, then BuildKit in Docker Engine will be used. Current Docker Engine version 20.10.17 embeds Buildkit 0.8.2 and therefore does not support subdir with git context. That's why you have [this warning message](https://github.com/moby/moby/blob/v20.10.17/vendor/github.com/moby/buildkit/source/gitidentifier.go#L50).

And yes it's recommended to use the `setup-buildx-action` because will create a `docker-container` builder using the latest stable version of BuildKit (0.10.4 atm).

Closing this issue since that should answer your question, but feel free to re-open if it doesn't. Thanks.

**Comment by almereyda** [comment]
I would consider this information very useful for the README of the build push action, why I suggest to reopen this ticket.

**Comment by crazy-max** [comment]
Sure sgtm
