### ISSUE TITLE
README "Git context" link doesn't link to anything

### ISSUE THREAD

**Issue by mattwelke** [docker/build-push-action#674]
### Docs

The README right now describes how the action works, and it has a paragraph that says:

> By default, this action uses the [Git context](https://github.com/docker/build-push-action#git-context) so you don't need to use the [actions/checkout](https://github.com/actions/checkout/) action to check out the repository because this will be done directly by [BuildKit](https://github.com/moby/buildkit).

Here, the link "Git context" links to the same section of the README that begins with this paragraph. It doesn't link to any new information to help the reader.

**Comment by polarathene** [comment]
I was also confused by that at first too, but understood when viewing the link URL that it was to reference that section.

The README has had some content shuffled around in the past, so it may not have originally been coupled so close to the section it links to right above it. And if it were re-located again, it'd helpful.

You wouldn't get much benefit from:

- **Git context**
- _Git context_
- "Git context"
- `Git context`
- Git context

Or similar alternative styling, but at least with the hyperlink to the section header, it does better establish "Git context" (both words together) as having meaning, referencing something. That may be less apparent with no styling, the link itself provides that added context :sweat_smile: 

---

That said, it took a while for me to grok:

- Two contexts are supported:
  - `git` (default):
    - The build context uses `git clone`, thus `actions/checkout` is not required to provide files.
    - Side-effect, `.dockerignore` has no effect apparently (_too late while populating the context content, or because no `.dockerignore` existed prior to `git clone` that the action will perform internally?_)
    - The `context` input for the action can specify a sub-directory of the clone to use for build context instead.
  - `path`:
    - The more familiar build context to developers building from local filesystem.
    - `.dockerignore` works as expected.
    - You just need to provide the files yourself, typically from `actions/checkout` and provide a path to `context`, with `context: .` being equivalent to `docker build .`.

Perhaps the README could be revised to better convey that information, or what else did you expect the current link to explain?

**Comment by mattwelke** [comment]
I think the solution would be to have someone familiar with the subject matter review the README and clean it up a bit. Context is that I'm coming from a relatively basic understanding of Docker. I build with `docker build` and concepts like "builders" go over my head. For GitHub Actions, I'm not familiar with "git context". I've always understood it that one has to use the "checkout" always as the first step. So it seems like there are some Docker concepts and GHA concepts I'm not familiar with, and having a README here explain how they go together would be nice.

**Comment by polarathene** [comment]
> For GitHub Actions, I'm not familiar with "git context". I've always understood it that one has to use the "checkout" always as the first step.

This `git` build context has nothing to do with Github Actions. It's about `docker build`.

Normally if you build a `Dockerfile` locally on your system it would use the "path" build context as the README describes (_I don't think that's an official name out of this action though_), and I'm not sure if `git` build context applies to a local git repo, or only as Docker docs describe (using a git URI) since those docs describe using `git clone` (_but they do not mention that `.dockerignore` in that git repo would be ignored, like this action does, that's often unexpected by users who have only used the "path" build context_)

Regarding `actions/checkout` you do this when you need access to your git repo in the job. This action will by default do it's own internal `git clone` instead, unless you change the build context with the action input `context: .`.

---

> So it seems like there are some Docker concepts and GHA concepts I'm not familiar with, and having a README here explain how they go together would be nice.

Fair. One of the maintainers can probably revise my attempt at better clarifying the two with a bullet list above.

Presently the two separate sections for each wasn't helpful as a user (_and I'm reasonably experienced with both GHA and Docker, I just never knew about the `git` build context_). It'd at least benefit with an overview of the two before branching off into sub-sections that provide further details.

**Comment by crazy-max** [comment]
Oh good catch it should redirect to docs website: https://docs.docker.com/engine/reference/commandline/build/#git-repositories

**Comment by polarathene** [comment]
> Oh good catch

Can you clarify on the `.dockerignore` compatibility?

> _Be careful because any file mutation in the steps that precede the build step will be ignored, including processing of the `.dockerignore` file since the context is based on the Git reference._

I'm not 100% if that is saying that any `.dockerignore` present prior does not affect the docker build context, but if the git repo has `.dockerignore` (at the appropriate place if a subdir is used?), then that `.dockerignore` is valid and will apply to the build context still? Or no `.dockerignore` is valid at all with the Git context?
