### ISSUE TITLE
How to speed up regular `docker build` runs in subsequent workflows?

### ISSUE THREAD

**Issue by sschuberth** [docker/build-push-action#681]
In contrast to [sharing data between jobs within the same workflow](https://github.com/docker/build-push-action/blob/master/docs/advanced/share-image-jobs.md), I'd like to speed up regular `docker build` runs in subsequent runs of a workflow.

My original assumption was that using `docker/build-push-action` with `cache-from/to: type=gha` would restore layers in a way that regular `docker build` in the same job would also benefit from the caching. However, [that does not seem to be the case](https://github.com/batect/batect/discussions/1245#discussioncomment-3497020).

So, if at all possible, how would I need to configure this action to leverage GitHub Actions cache in a way so that `docker build` runs / third-party tools like [Batect](https://github.com/batect/batect) benefit from the layers restored from the cache?

**Comment by polarathene** [comment]
Presumably because using `docker build` differs in where to look for cache?

There is a build option that might be of use [`--cache-from`](https://docs.docker.com/engine/reference/commandline/build/#specifying-external-cache-sources), although that looks like you might need to have `build-push-action` use a different cache exporter than `type=gha`?

There's also the default container driver used by the action, which IIRC you can opt-out of for local `docker` driver instead. I haven't looked at the action docs in a bit, but recall this loses some features (_multi-platform build is one I think_), but that may provide a compatible local cache that `docker build` can share?

**Comment by crazy-max** [comment]
> My original assumption was that using `docker/build-push-action` with `cache-from/to: type=gha` would restore layers in a way that regular `docker build` in the same job would also benefit from the caching. However, [that does not seem to be the case](https://github.com/batect/batect/discussions/1245#discussioncomment-3497020).

It will not if you don't specify cache exporters in other build commands like: `docker buildx build --cache-from type=gha --cache-to type=gha,mode=max .`. Also as you're using the `gha` cache, if this command runs outside an action with `run:` in a step you have to expose the runtime as explained in https://github.com/moby/buildkit#github-actions-cache-experimental

Closing this issue since that should answer your question, but feel free to re-open if it doesn't. Thanks.
