### ISSUE TITLE
Slow image loading with `load: true`

### ISSUE THREAD

**Issue by PaulMorrisPP** [docker/build-push-action#998]
### Description

I'm not sure if this is a bug or a feature request, but we're seeing large image load times that we wouldn't expect to see when building normally. That is, we're using this action to build one of our Docker Compose images manually, specifically because we want to leverage GHA caching. The whole setup works, but after buildx finishes its work and hands off the image to Docker, it builds a tarball and imports it into the image store. This import operation actually takes more time (77s) than building the image itself (60s).

This performance hole is something we would like to avoid and we want to understand if it's something we're doing wrong or just a defect in the way the image is loaded (using `load: true`), because it certainly seems to be the case that building large images does not normally take this long to load into the image store.

It seems to me we really just want to be able to specify an uncompressed output using something like `--output type=image,name=...,compression=uncompressed`, but it looks like this action does not support the compression option.

### Partial build output
```
#18 exporting to docker image format
#18 exporting layers
#18 exporting layers 4.6s done
#18 exporting manifest sha256:9a5bb6d6c26ad15fae8c7f8d46b483f78d0caab77b4d167441bdbb9a1eb47fef done
#18 exporting config sha256:b4dc547a4f859a30c5397e88fc3ec0a6014ff432d988885120de7871b4853e1d done
#18 sending tarball
#18 ...

#19 importing to docker
#19 DONE 59.8s

#18 exporting to docker image format
#18 sending tarball 72.4s done
#18 DONE 77.0s
```

**Comment by crazy-max** [comment]
> Slow image loading with `load: true`

Status of uploading build result to the Docker store when using the container driver will be available on next Buildx 0.12 release: https://github.com/docker/buildx/pull/1994

> This performance hole is something we would like to avoid

Showing your workflow would help to understand but I assume you're using the `setup-buildx-action` and therefore a [container builder](https://docs.docker.com/build/drivers/docker-container/). In that case it can take quite some time to load the image to the Docker store.

**Comment by PaulMorrisPP** [comment]
Correct, but why? The internal Docker builder is fast to load images, presumably because it uses some internal routine to transfer the image. Why is the container builder so much slower?

**Comment by kwikwag** [comment]
:+1: My use case: build has to download a 6Gb file from Huggingface. Downloading that takes considerably longer than downloading the cache. Then, specifying `load: true` is also very slow. Building the image from scratch is about 3m, while loading from cache is about 8m. Counterintuitive. See also [my Stackoverflow post]( https://stackoverflow.com/questions/77494739)

**Comment by kwikwag** [comment]
FWIW I created a [sample repo with GitHub actions](https://github.com/kwikwag/issue-docker-gha-load-very-slow/actions/workflows/jobs.yaml) that demonstrate it. The idea is to create a large layer and check performance when building the image in either of three ways: Docker build action with `gha` cache, Docker build action without cache, and a Docker `buildx build` command in `bash`. I tried a few different scenarios, and after each of them I triggered an additional run so that I could see how the cache is used. Here's the list of the scenarios I tested:
 
<table>
  <tr><th rowspan="2">scenario</th><th rowspan="2">stage</th><th colspan="3">timings</th></tr>
  <tr><th>action with cache</th><th>action without cache</th><th class=warning>no action, inline build</th></tr>

<tr>
  <td rowspan="2">Generate 500Mb file  (not from network)</td>
  <td><a href="https://github.com/kwikwag/issue-docker-gha-load-very-slow/actions/runs/6913692118">first commit</a> 
 </td>
  <td>51s</td><td>46s</td><td>19s</td>
</tr>
<tr>
  <td><a href="https://github.com/kwikwag/issue-docker-gha-load-very-slow/actions/runs/6913697024">re-trigger</a>
  </td>
  <td>34s</td><td>42s</td><td>19s</td>
</tr>


<tr>
  <td rowspan="2">Generate 2Gb file (not from network)</td>
  <td><a href="https://github.com/kwikwag/issue-docker-gha-load-very-slow/actions/runs/6913703071">first commit</a> 
 </td>
  <td>174s</td><td>133s</td><td>63s</td>
</tr>
<tr>
  <td><a href="https://github.com/kwikwag/issue-docker-gha-load-very-slow/actions/runs/6913715038">re-trigger</a>
  </td>
  <td>113s</td><td>133s</td><td>63s</td>
</tr>


<tr>
  <td rowspan="2">Add stress</td>
  <td><a href="https://github.com/kwikwag/issue-docker-gha-load-very-slow/actions/runs/6913756449">first commit</a> 
 </td>
  <td>216s</td><td>176s</td><td>98s</td>
</tr>
<tr>
  <td><a href="https://github.com/kwikwag/issue-docker-gha-load-very-slow/actions/runs/6913783100">re-trigger</a>
  </td>
  <td>109s</td><td>180s</td><td>105s</td>
</tr>


<tr>
  <td rowspan="2">Download 1.5Gb file</td>
  <td><a href="https://github.com/kwikwag/issue-docker-gha-load-very-slow/actions/runs/6913825934">first commit</a> 
  </td>
  <td>147s</td><td>112s</td><td>33s</td>
</tr>
<tr>
  <td><a href="https://github.com/kwikwag/issue-docker-gha-load-very-slow/actions/runs/6913843591">re-trigger</a>
  </td>
  <td>106s</td><td>100s</td><td>38s</td>
</tr>



<tr>
  <td rowspan="2">Download 1.5Gb + split into many files</td>
  <td><a href="https://github.com/kwikwag/issue-docker-gha-load-very-slow/actions/runs/6914022411">first commit</a> 
  </td>
  <td>117s</td><td>112s</td><td>43s</td>
</tr>
<tr>
  <td><a href="https://github.com/kwikwag/issue-docker-gha-load-very-slow/actions/runs/6914070127">re-trigger</a>
  </td>
  <td>93s</td><td>111s</td><td>43s</td>
</tr>

</table>

From what I can tell, the actions are simply limited by I/O. The only scenario where cache improves performance is when stressing the CPU during build. The rest show a 20% gain at most. This still seems counter-intuitive, as the most common scenario for a Dockerfile is installing dependencies required for run.

Also, still surprisingly to me, running a Docker build action as part of a bash script is still the quickest by a factor of x2 to x3 faster - which means the majority of the I/O bottleneck is how the build action step is set-up. It adds a lot of I/O which is the limiting factor.

**Comment by kwikwag** [comment]
Another observation: this is probably because of the use of the `docker-container` driver. It effectively triples the I/O required to build the image when using `--load`. A solution would be to either reduce the I/O required for `--load`, or to allow `gha` cache use to happen with the `docker` driver.

**Comment by kwikwag** [comment]
And just a bit more: running to-and-from the GHCR is much faster than `--load` which again is counter-intuitive. See [this workflow run](https://github.com/kwikwag/issue-docker-gha-load-very-slow/actions/runs/6914885090).

**Comment by kwikwag** [comment]
@crazy-max Any ideas? Is there any way to utilize GHA cache for Docker builds in Github Actions without paying a performance penalty? I can think of either of the following paths as a possible solution, but I am pretty oblivious to the inner workings: (1) somehow do direct I/O between the container and the host which prevents disk I/O, perhaps avoiding the tarring and/or transfer, similar to what is happening when using GHCR; (2) implementing cache for the docker driver, so the images are directly built on the host docker; (3) adding a special cache that writes directly to the host docker, thereby avoiding the need to TAR and transfer the layers.

**Comment by crazy-max** [comment]
> Correct, but why? The internal Docker builder is fast to load images, presumably because it uses some internal routine to transfer the image. Why is the container builder so much slower?

Because a build using the `docker-container` driver does not have direct access to the Docker store and therefore needs to load back build result to it whereas the `docker` driver has direct access.

**Comment by ozancaglayan** [comment]
Hi, I don't know why was this closed as `completed`. Is there a solution nowadays for this problem?

The fact that an image is not easily accessible from later `steps` using the `container` driver can even be considered a regression. The container driver is the recommended driver as it supports caching and multi-platform builds. If we switch to the classical driver for faster and accessible builds, we lose the caching and multi-platform builds.

I'm really stuck with this as apparently there's no reasonable solution to achieve:
- build but not push
- test
- push if tests succeed

using `container` driver.

Would exporting to local folder and/or `tar` and then using `docker import` be faster than `load: true` or are they the same thing?

Thanks!

**Comment by nivetaiyer** [comment]
I'm having a similar issue. My image contains torch and other cuda libs that are built from scratch - it takes ~ 30 min to build without caching. With caching, build time reduces to ~ 2 min, but load=True takes an additional ~5 minutes which is annoying. I'm also trying a workflow that can build -> test via docker run -> push to ecr if tests pass. It takes too long with load=True.

**Comment by ValdikSS** [comment]
I, too, had this issue, but I solved it the other way.

You see, build-push-action caching subsystem is for caching layers _for building process_. If you only need to build a container to use it later in subsequent runs, you don't need your building process cached — just cache the final result, the resulting image.

This could be done by **not** using `docker/setup-buildx-action` (so all the building is done using regular docker storage driver where build-push-action's `load` is almost instant), and using [ScribeMD/docker-cache](https://github.com/ScribeMD/docker-cache), it will automatically save your image in GH cache and load it every time.


```
    - name: Cache Docker images
      id: docker-cache
      uses: ScribeMD/docker-cache@0.5.0
      with:
        key: docker-${{ runner.os }}

    - name: Build Docker image
      if: steps.docker-cache.outputs.cache-hit != 'true'
      uses: docker/build-push-action@v6
```
